line-length = 80
indent-width = 4

[lint]
select = [
    "F", # flake8
    "I", # isort
    "TID", # flake8-tidy-imports
    "T20", # flake8-print
    "N", # pep8-naming
    "C4", # flake8-comprehensions,
    "D", # pydocstyle
    "ANN", # flake8-annotations
]

ignore = [
    "D203", # one-blank-line-before-class
    "D213", # multi-line-summary-second-line
    "D205", # blank-line-after-summary
    "D407", # dashed-underline-after-section
    "D400", # ends-in-period
    "D415", # ends-in-punctuation
    "ANN204", # missing-return-type-special-method
    "ANN101", # missing-type-self
]

[format]
quote-style = "single"
indent-style = "space"
line-ending = "lf"
skip-magic-trailing-comma = false

